# Generated by Django 4.1.7 on 2023-03-31 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_map_alter_message_date_alter_room_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='user1',
            new_name='roomid',
        ),
        migrations.RemoveField(
            model_name='map',
            name='user2',
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 31, 8, 7, 42, 996600)),
        ),
        migrations.AlterField(
            model_name='room',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 31, 8, 7, 42, 996600)),
        ),
    ]
