# Generated by Django 4.1.7 on 2023-03-31 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_rename_user1_map_roomid_remove_map_user2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('online', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 31, 17, 6, 49, 302608)),
        ),
        migrations.AlterField(
            model_name='room',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 31, 17, 6, 49, 302608)),
        ),
    ]
