# Generated by Django 4.1.7 on 2023-03-31 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_active_alter_message_date_alter_room_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='active_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='active',
            name='offline_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 31, 17, 23, 43, 552062)),
        ),
        migrations.AlterField(
            model_name='room',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 31, 17, 23, 43, 552062)),
        ),
    ]
